/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as SignInRouteImport } from './sign-in'
import { Route as AuthRouteImport } from './_auth'
import { Route as SplatRouteImport } from './$'
import { Route as IndexRouteImport } from './index'
import { Route as AuthLayoutRouteImport } from './_auth._layout'
import { Route as AuthLayoutExploreRouteImport } from './_auth._layout.explore'
import { Route as AuthLayoutBookshelfRouteImport } from './_auth._layout.bookshelf'
import { Route as AuthLayoutBookIdRouteImport } from './_auth._layout.book.$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutExploreRoute = AuthLayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutBookshelfRoute = AuthLayoutBookshelfRouteImport.update({
  id: '/bookshelf',
  path: '/bookshelf',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutBookIdRoute = AuthLayoutBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => AuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sign-in': typeof SignInRoute
  '/bookshelf': typeof AuthLayoutBookshelfRoute
  '/explore': typeof AuthLayoutExploreRoute
  '/book/$id': typeof AuthLayoutBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sign-in': typeof SignInRoute
  '/bookshelf': typeof AuthLayoutBookshelfRoute
  '/explore': typeof AuthLayoutExploreRoute
  '/book/$id': typeof AuthLayoutBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_auth/_layout/bookshelf': typeof AuthLayoutBookshelfRoute
  '/_auth/_layout/explore': typeof AuthLayoutExploreRoute
  '/_auth/_layout/book/$id': typeof AuthLayoutBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/sign-in' | '/bookshelf' | '/explore' | '/book/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/sign-in' | '/bookshelf' | '/explore' | '/book/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_auth'
    | '/sign-in'
    | '/_auth/_layout'
    | '/_auth/_layout/bookshelf'
    | '/_auth/_layout/explore'
    | '/_auth/_layout/book/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_layout/explore': {
      id: '/_auth/_layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthLayoutExploreRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/bookshelf': {
      id: '/_auth/_layout/bookshelf'
      path: '/bookshelf'
      fullPath: '/bookshelf'
      preLoaderRoute: typeof AuthLayoutBookshelfRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/book/$id': {
      id: '/_auth/_layout/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof AuthLayoutBookIdRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutBookshelfRoute: typeof AuthLayoutBookshelfRoute
  AuthLayoutExploreRoute: typeof AuthLayoutExploreRoute
  AuthLayoutBookIdRoute: typeof AuthLayoutBookIdRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutBookshelfRoute: AuthLayoutBookshelfRoute,
  AuthLayoutExploreRoute: AuthLayoutExploreRoute,
  AuthLayoutBookIdRoute: AuthLayoutBookIdRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
